### ISSUE TITLE
source vs. exécution

### ISSUE THREAD

**Issue by a-tsioh** [MathildeCh/PPE1#2]
https://github.com/MathildeCh/exo_PPE/blob/59943f1061ff6f1c8688532ade98774bbfd61657/Exercice/exo1_part2.sh#L1

Attention, il y a des différences subtiles entre utiliser `source` et simplement lancer le second script (en le rendant exécutable ou avec la commande `bash`). 
Plus de détails ici : https://superuser.com/questions/176783/what-is-the-difference-between-executing-a-bash-script-vs-sourcing-it
a priori je ne pensais pas trop aborder `source` mais puisque vous l'avez trouvé !
 (c'est très utile par exemple pour les venv python que vous connaissez peut-être ou découvrirez bientôt)

**Comment by MathildeCh** [comment]
D'accord, merci beaucoup!
